snappy-master/config/routes.rb
Rails.application.routes.draw do
  

  resources :weddings

  devise_for :users, controllers: {registrations: "registrations"}
  root 'pages#home'

end

snappy-master/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

validates_presence_of :name

has_many :wedding

end

snappy-master/app/models/wedding.rb
class Wedding < ActiveRecord::Base

	validates_presence_of :name
	validates_presence_of :email
	validates_presence_of :date
	validates_presence_of :user_id
	belongs_to :user
	
end

snappy-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

snappy-master/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

snappy-master/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private 

	def sign_up_params
		params.require(:user).permit(:name, :email, :password)
	end

	def account_update_params
		params.require(:user).permit(:name, :email, :password, :current_password)
	end
end

snappy-master/app/controllers/weddings_controller.rb
class WeddingsController < ApplicationController
  before_action :set_wedding, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @weddings = Wedding.all
    respond_with(@weddings)
  end

  def show
    respond_with(@wedding)
  end

  def new
    @wedding = Wedding.new
    respond_with(@wedding)
  end

  def edit
  end

  def create
    @wedding = Wedding.new(wedding_params)
    @wedding.save
    respond_with(@wedding)
  end

  def update
    @wedding.update(wedding_params)
    respond_with(@wedding)
  end

  def destroy
    @wedding.destroy
    respond_with(@wedding)
  end

  private
    def set_wedding
      @wedding = Wedding.find(params[:id])
    end

    def wedding_params
      params.require(:wedding).permit(:name, :date, :location, :guests, :user_id)
    end
end

snappy-master/app/helpers/application_helper.rb
module ApplicationHelper
end

snappy-master/app/helpers/pages_helper.rb
module PagesHelper
end

snappy-master/app/helpers/weddings_helper.rb
module WeddingsHelper
end

snappy-master/app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Snappy", root_path, class: "navbar-brand" %>
    </div>
 
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li><%= link_to "Your Wedding", weddings_path %> </li>
      </ul>
    
      <ul class="nav navbar-nav navbar-right">
<% if current_user %>
<li> <%= link_to "Settings", edit_user_registration_path %></li>
<li> <%= link_to "Logout", destroy_user_session_path, method: :delete %></li>

<% else %>

<li> <%= link_to "Login", new_user_session_path %> </li>
<li> <%= link_to "Signup", new_user_registration_path %> </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

snappy-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Snappywedding</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/header" %>
<div class="container">
<% flash.each do |type, message| %>
<div class="alert alert-info fadee-in">
	<button class="close" data-dismiss="alert">x</button>
	<%= message %>
	</div>
<% end %>
<% if current_page?(root_path)%>
<div class="landing">
	<% else %>
	<div class="container">
		<% end %>
<%= yield %>
</div>
</body>
</html>

snappy-master/app/views/pages/home.html.erb
<div class="text-center landing_title">
	<%= link_to 'Start Here', weddings_path, class: "btn btn-default btn-lg" %>
</div>

snappy-master/app/views/weddings/_form.html.erb
<%= simple_form_for(@wedding) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :date %>
    <%= f.input :location %>
    <%= f.input :guests %>
    <%= f.input :user_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

snappy-master/app/views/weddings/edit.html.erb
<h1>Editing wedding</h1>

<%= render 'form' %>

<%= link_to 'Show', @wedding %> |
<%= link_to 'Back', weddings_path %>

snappy-master/app/views/weddings/index.html.erb
<h1>Listing weddings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Location</th>
      <th>Guests</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @weddings.each do |wedding| %>
      <tr>
        <td><%= wedding.name %></td>
        <td><%= wedding.date %></td>
        <td><%= wedding.location %></td>
        <td><%= wedding.guests %></td>
        <td><%= wedding.user_id %></td>
        <td><%= link_to 'Show', wedding %></td>
        <td><%= link_to 'Edit', edit_wedding_path(wedding) %></td>
        <td><%= link_to 'Destroy', wedding, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wedding', new_wedding_path %>

snappy-master/app/views/weddings/new.html.erb
<h1>New wedding</h1>

<%= render 'form' %>

<%= link_to 'Back', weddings_path %>

snappy-master/app/views/weddings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wedding.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @wedding.date %>
</p>

<p>
  <strong>Location:</strong>
  <%= @wedding.location %>
</p>

<p>
  <strong>Guests:</strong>
  <%= @wedding.guests %>
</p>

<p>
  <strong>User:</strong>
  <%= @wedding.user_id %>
</p>

<%= link_to 'Edit', edit_wedding_path(@wedding) %> |
<%= link_to 'Back', weddings_path %>